### PR TITLE
Feature/monitor changes

### PR DESCRIPTION
**Pull request by arnar-steinthors**
Additional support for #15 allowing users to monitor changes to both the push token and the activity status through a stream.

### CODE REVIEW

**Comment by jolamar** [comment]
I tested and it works. Here's how I'm listening:
```
_liveActivitiesPlugin.activityUpdateStream.listen((activity) {
        print(activity);
      });
```

Here are some of the updates I got:
- `_ActiveActivityUpdate`
- `_EndedActivityUpdate`

**Comment by jolamar** [comment]
unrelated to this PR but are you seeing this message in Flutter when sending push notifications?
>Unable to decode content state: The data couldn’t be read because it is missing.

**Comment by istornz** [comment]
Published v1.6.0, thanks guys 👍 
(@arnar-steinthors you just forget to update ```README.md```, I updated for you, is it OK ?)

**Comment by jolamar** [comment]
@istornz looks like you left some content regarding "Picture removed". I'd just say it returns status updates for new push tokens or when the activity ends. 

I imagine once @arnar-steinthors or myself finish our projects we'll contribute examples to the docs of how to use push tokens and lifecycle events.

**Comment by arnar-steinthors** [comment]
> I tested and it works. Here's how I'm listening:
> 
> ```
> _liveActivitiesPlugin.activityUpdateStream.listen((activity) {
>         print(activity);
>       });
> ```
> 
> Here are some of the updates I got:
> 
> * `_ActiveActivityUpdate`
> * `_EndedActivityUpdate`

Awesome, I will test this on production on monday/tuesday when the backend is ready to see how it goes when the app has been in the background for some time.

**Comment by arnar-steinthors** [comment]
> Published v1.6.0, thanks guys 👍 (@arnar-steinthors you just forget to update `README.md`, I updated for you, is it OK ?)

Sorry I forgot about that 😶‍🌫️ thanks for taking care of it 👏

Only have the same comment that @jolamar left about the return value for the new docs

`Stream<ActivityUpdate> Picture removed`

**Comment by arnar-steinthors** [comment]
> unrelated to this PR but are you seeing this message in Flutter when sending push notifications?
> 
> > Unable to decode content state: The data couldn’t be read because it is missing.

@jolamar  Yes I am receiving it, I think its because of the original ContentState thats inside the source code but everything is still working when I am testing locally, will have to see if it still works when I end to end test this on monday/tuesday

**Comment by istornz** [comment]
@arnar-steinthors @jolamar Oops my bad, fixed it. Thanks !

**Comment by arnar-steinthors** [comment]
@jolamar I also have some thoughts on the `.getPushToken()` method you added.

1. If i am running my app on a simulator and call the method it will hang forever, probably because there are no updates to the token in the native code.
2. If I am running on a physical device the method will return a token but if I call the method consecutively it will hang on the second call, probably waiting for an update.

pseudocode example
```dart
final plugin = LiveActivities();
var token = await plugin.getPushToken(); // a token is returned
token = await plugin.getPushToken(); // the method will hang, never returning a value
```

What do you think about either removing this from the api since we now have the stream or changing the native implementation to use
```swift
let token = activity.pushToken;
result(token) // returns a nullable string
```
instead of what we currently have
```swift
for await data in activity.pushTokenUpdates {
            let pushToken = data.map {String(format: "%02x", $0)}.joined()
            result(pushToken) // returns a token when there is an update
          }
```

Then it would (hopefully) just return null on simulators and an identical token if you chain the calls

**Comment by jolamar** [comment]
@arnar-steinthors that is also happening to me.. I assume that's just a weird side effect of using `pushTokenUpdates` maybe it gets it initially then immediately updates it? It doesn't really bug me that much :) 

So I got everything working and I'm responding to dismisses and token updates. My implementation looks like this.. I'd like to hear your thoughts.

```
WidgetsBinding.instance.addPostFrameCallback((_) {
        _liveActivitiesPlugin.activityUpdateStream.listen((activity) {
          LiveActivityState state;
          String pushToken;
          activity.map(
            active: (newActivity) {
              state = LiveActivityState.active;
              pushToken = newActivity.activityToken;
            },
            ended: (_) => state = LiveActivityState.ended,
            unknown: (_) => state = LiveActivityState.unknown,
          );

          switch (state) {
            case LiveActivityState.active:
              context.read<MyStore>().setLiveActivityPushToken(pushToken, activity.activityId);
              break;
            case LiveActivityState.ended:
              context.read<MyStore>().revokeLiveActivityPushToken(activity.activityId);
              break;
            case LiveActivityState.unknown:
              break;
          }
        });
      });
```

I tried using `_liveActivitiesPlugin.getActivityState(activityId)` in the listener but I don't think the state had been set yet so I wasn't getting end state updates, so I used the map instead.

**Comment by jolamar** [comment]
@arnar-steinthors I like your pushToken suggestion. I also get the hung behavior in simulator so this would be a great fix!

**Comment by jolamar** [comment]
@arnar-steinthors I spent a lot of time yesterday trying to manage state for multiple live activities and hit a wall. Wondered if you have address this? Basically sharedDefaults isn't unique across live activities so all of them share the same data. I tried adding an ID to the sharedDefault key but that caused live activities to not appear at all. Not sure where to go from here.

**Comment by arnar-steinthors** [comment]
> @arnar-steinthors that is also happening to me.. I assume that's just a weird side effect of using `pushTokenUpdates` maybe it gets it initially then immediately updates it? It doesn't really bug me that much :)
> 
> So I got everything working and I'm responding to dismisses and token updates. My implementation looks like this.. I'd like to hear your thoughts.
> 
> ```
> WidgetsBinding.instance.addPostFrameCallback((_) {
>         _liveActivitiesPlugin.activityUpdateStream.listen((activity) {
>           LiveActivityState state;
>           String pushToken;
>           activity.map(
>             active: (newActivity) {
>               state = LiveActivityState.active;
>               pushToken = newActivity.activityToken;
>             },
>             ended: (_) => state = LiveActivityState.ended,
>             unknown: (_) => state = LiveActivityState.unknown,
>           );
> 
>           switch (state) {
>             case LiveActivityState.active:
>               context.read<MyStore>().setLiveActivityPushToken(pushToken, activity.activityId);
>               break;
>             case LiveActivityState.ended:
>               context.read<MyStore>().revokeLiveActivityPushToken(activity.activityId);
>               break;
>             case LiveActivityState.unknown:
>               break;
>           }
>         });
>       });
> ```
> 
> I tried using `_liveActivitiesPlugin.getActivityState(activityId)` in the listener but I don't think the state had been set yet so I wasn't getting end state updates, so I used the map instead.

Sorry for the late reply but yeah it looks good as long as this Widget that you are using this method in will live as long as the app does (i.e is never disposed unless the app is killed), otherwise you never stop listening to the stream and could end up with identical listeners.

You could also simplify this
```dart
WidgetsBinding.instance.addPostFrameCallback((_) {
        _liveActivitiesPlugin.activityUpdateStream.listen((activity) {
          activity.map(
            active: (newActivity) {
              context.read<MyStore>().setLiveActivityPushToken(newActivity.activityToken, activity.activityId);
            },
            ended: (_) =>  context.read<MyStore>().revokeLiveActivityPushToken(activity.activityId),
            unknown: (_) {},
          );
      });
```

**Comment by arnar-steinthors** [comment]
> @arnar-steinthors I spent a lot of time yesterday trying to manage state for multiple live activities and hit a wall. Wondered if you have address this? Basically sharedDefaults isn't unique across live activities so all of them share the same data. I tried adding an ID to the sharedDefault key but that caused live activities to not appear at all. Not sure where to go from here.
> 
> I tried adding a unique id to the key again today and it worked so I created a PR if you want to see #22

No I havent thought about this issue, my implementation prohibits using multiple activities at the same time since it doesnt fit my usecase.

I took a quick look at the PR and it looks a bit hacky but I guess we cant get around it since we are quite limited. I am wondering though if we need the extra attribute `var sharedId: String`, could we not use `var id = UUID()` for the same purpose?

**Comment by jolamar** [comment]
@arnar-steinthors it's totally hacky. We need to pass in a unique ID at time of creation so that we can give the sharedDefault keys an ID. `var id = UUID()` doesn't exist until after the live activity is created. I bet others will want to supports multiple live activities, in my use case I want to be able to track multiple live sporting events.

**Comment by adham-ashraf77** [comment]
@jolamar  I need help creating a live activity that does not appear, please

**Pull request merged**
