### PR TITLE
🐞Fix a bug where init never completes

### PR DESCRIPTION
**Pull request by JulianBissekkou**

### CODE REVIEW

**Comment by JulianBissekkou** [comment]
I will do some testing with other methods as well and if that's done remove the draft status

**Comment by istornz** [comment]
@JulianBissekkou Nice catch !
Tell me when it's ready to merge 👍 
Thanks !

**Comment by JulianBissekkou** [comment]
Ready to merge

**Comment by istornz** [comment]
Thanks !

**Pull request merged**
