### PR TITLE
Add update live activity with alert config

### PR DESCRIPTION
**Pull request by charlesRmajor**
Adds support for Alert Config, which causes the live activity to send notification ping/vibration/wake screen

### CODE REVIEW

**Comment by istornz** [comment]
Hi @charlesRmajor, thanks for your PR 👍 

I will release a new update of the plugin including your feature soon.

**Comment by notTural** [comment]
Hi @istornz. Thanks a lot for the great package. When will you be releasing this feature?

**Comment by charlesRmajor** [comment]
@istornz — I think this hasn't been release yet? If that's true, maybe hold off. I'll submit a PR in a bit updating to use the new 'update' function. Apple has [deprecated the old one](https://developer.apple.com/documentation/activitykit/activity/update(using:)) ... keeping us on our toes, eh?

I'll include being able to set the staleIn the same was as the package currently has for 'create'

**Comment by istornz** [comment]
Hello 👋 
This feature is already available with the latest version of the package 👌

Perfect @charlesRmajor I will release a new version once it will be done.
Thanks 🙏

**Pull request merged**
